name: Build test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup node
      uses: actions/setup-node@master
    
    - name: Build
      run: |
        npm install -g nw-builder@3.6.0
        nwbuild -p win32,win64,osx64,linux32,linux64 .
    
    - name: Pack
      run: |
        zip -r CCHv2.${{ github.run_id }}.win32.zip . -i "build/CodeForces Contest Helper v2/win32/*"
        zip -r CCHv2.${{ github.run_id }}.win64.zip . -i "build/CodeForces Contest Helper v2/win64/*"
        tar -zcvf CCHv2.${{ github.run_id }}.osx64.tar.gz "./build/CodeForces Contest Helper v2/osx64/"
        tar -zcvf CCHv2.${{ github.run_id }}.linux32.tar.gz "./build/CodeForces Contest Helper v2/linux32/"
        tar -zcvf CCHv2.${{ github.run_id }}.linux64.tar.gz "./build/CodeForces Contest Helper v2/linux64/"
    
    - uses: actions/upload-artifact@v2
      with:
        name: CCHv2.${{ github.run_id }}.win32.zip
        path: CCHv2.${{ github.run_id }}.win32.zip
    - uses: actions/upload-artifact@v2
      with:
        name: CCHv2.${{ github.run_id }}.win64.zip
        path: CCHv2.${{ github.run_id }}.win64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: CCHv2.${{ github.run_id }}.osx64.tar.gz
        path: CCHv2.${{ github.run_id }}.osx64.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: CCHv2.${{ github.run_id }}.linux32.tar.gz
        path: CCHv2.${{ github.run_id }}.linux32.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: CCHv2.${{ github.run_id }}.linux64.tar.gz
        path: CCHv2.${{ github.run_id }}.linux64.tar.gz
