name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get the version
      id: get_version
      shell: bash
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=VERSION::$VERSION
    
    - name: Setup node
      uses: actions/setup-node@master
    
    - name: Build
      run: |
        npm install -g nw-builder@3.6.0
        nwbuild -p win32,win64,osx64,linux32,linux64 .
    
    - name: Pack
      run: |
        zip -r CCHv2.${{ steps.get_version.outputs.VERSION }}.win32.zip . -i "build/CodeForces Contest Helper v2/win32/*"
        zip -r CCHv2.${{ steps.get_version.outputs.VERSION }}.win64.zip . -i "build/CodeForces Contest Helper v2/win64/*"
        tar -zcvf CCHv2.${{ steps.get_version.outputs.VERSION }}.osx64.tar.gz "./build/CodeForces Contest Helper v2/osx64/"
        tar -zcvf CCHv2.${{ steps.get_version.outputs.VERSION }}.linux32.tar.gz "./build/CodeForces Contest Helper v2/linux32/"
        tar -zcvf CCHv2.${{ steps.get_version.outputs.VERSION }}.linux64.tar.gz "./build/CodeForces Contest Helper v2/linux64/"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: true
        files: |
          CCHv2.${{ steps.get_version.outputs.VERSION }}.win32.zip
          CCHv2.${{ steps.get_version.outputs.VERSION }}.win64.zip
          CCHv2.${{ steps.get_version.outputs.VERSION }}.osx64.tar.gz
          CCHv2.${{ steps.get_version.outputs.VERSION }}.linux32.tar.gz
          CCHv2.${{ steps.get_version.outputs.VERSION }}.linux64.tar.gz
        name: CCHv2 ${{ steps.get_version.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
